### ISSUE TITLE
"Save Layout" function is not working in Binary Mode.

### ISSUE THREAD

**Issue by Wooopz** [farrellf/TelemetryViewer#10]
The function "Save Layout" is not working in Binary Mode (it works in CSV but not in Binary).
When you click on "Save Layout" button in binary mode, a empty file is generated.
It is really boring to reconfigure all layout each time i restart the software.
Could you correct this bug please. Thank you.

**Comment by Lecerof** [comment]
Hi, do you mind testing out the version I have on my github. I think I have resolved this issue but I am not sure because I do not have any good means of testing it out. Athough, the layout is slightly different on my version, I think you will understand it without any further instructions.

**Comment by farrellf** [comment]
It looks like Lecerof fixed the problem by checking if the ChecksumProcessor is null. I've always used a checksum so forgot about that. Wooopz, can you confirm if that fixed your problem?

**Comment by Wooopz** [comment]
Yes. The Lecerof version fixed the problem. Thank you.

**Comment by farrellf** [comment]
This was fixed as part of version 0.5:
https://github.com/farrellf/TelemetryViewer/commit/3f37052542cb0d5df20aa85120ef81fa4a443fb9

If there are no objections, I'll close this issues in a few days.

**Comment by farrellf** [comment]
Closing
