### ISSUE TITLE
Question on max input size

### ISSUE THREAD

**Issue by mjs513** [farrellf/TelemetryViewer#12]
Hi
First this is a great viewer for telemetry. So this is more of a question than an issue, well maybe.

We are probably pushing this to the limits but we are passing it 36 floats for a total length of 1116 chars on input to the viewer.  I can't seem to get it to display anything.  Was wondering if its me or there is some sort of max size on the number of input chars?

Thanks
Mike

**Comment by Lecerof** [comment]
Does it work with less floats?

**Comment by mjs513** [comment]
Hi Lecerof,
Finally got it working.  Was a problem with data format.  When I posted it looked ok but didn't work.  I reformatted the data and now have it working.  Up to 77 floats being sent.  But with that many I can't get all them on the chart window.  Really needs to be a scrolling window.  Going to close as that's a separate issue

Mike

**Comment by mjs513** [comment]
Oh no.  Sorry for the confusion.
 In the pop up window where you select what to plot on a chart and where you select the chart to plot I can't see all the variables (with the check boxes), the window goes off the screen.  I haven't been able to resize it or figure out how to see the rest of the variables.  Think I can see about 15 give or take of the variables.  Even the OK button is off the screen.

**Comment by Lecerof** [comment]
I see, i figured it out when i tried it myself. I might be able to make a fix for it next week if you dont do it yourself. If you do, push it to a fork and I can pull it to my version of the program.

**Comment by mjs513** [comment]
Unfortunately I don't know enough about Java to figure that one out.  Have enough challenges with c++.  If you do it let me know :)

**Comment by mjs513** [comment]
I just looked at your fork - looks like you added a bunch of functionality that I wished Telemetry viewer had.  Nice Work!

**Comment by mjs513** [comment]
Ok.  I give up - tried adding the scrollbar but no luck. probably adding it wrong:  This is what I added but it just gives me the header:
`		//------
		//JScrollPane scrollPane = new JScrollPane(windowContents);
		JScrollPane scrollPane=new JScrollPane(windowContents,
				ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED,
				ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		setContentPane(scrollPane);
		scrollPane.setViewportView(windowContents);
		windowContents.setBorder(new EmptyBorder(10, 10, 10, 10));
		//windowContents.setLayout(new BoxLayout(windowContents, BoxLayout.Y_AXIS));
		windowContents.setPreferredSize(new Dimension(150, 410));
		add(windowContents);`
