### ISSUE TITLE
Output GUI Tools

### ISSUE THREAD

**Issue by rummanwaqar** [farrellf/TelemetryViewer#13]
It will be very useful to add tools to write to serial output using gui tools.

**Comment by rummanwaqar** [comment]
I started working on it in my fork but I am not really a Java programmer so progress is slow

**Comment by farrellf** [comment]
I plan to add support for this, but it might be a while before I get to it.

**Comment by rummanwaqar** [comment]
It would be good to just have a serial terminal. We can log raw messages and send messages. Currently my fork uses the terminal to read and send messages.

**Comment by farrellf** [comment]
I finally got around to implementing this. It's in the latest release:

http://www.farrellf.com/projects/software/2021-07-24_Telemetry_Viewer_v0.8/
https://www.youtube.com/watch?v=NUBm9b8YQMQ&t=937s
