### ISSUE TITLE
Can't edit the CSV Packet Data Structure

### ISSUE THREAD

**Issue by metaphoric** [farrellf/TelemetryViewer#23]
once defined, we can't edit the CSV Packet Data Structure anymore

**Comment by MiloMindbender** [comment]
It is actually fairly easy to edit the layout file with any text editor.  I've found this is the easiest way to handle a change in the data structure.  It's not so good for editing the layout of the charts/graphs, but for changing the data structure a text editor like Notepad++ works pretty well.

**Comment by farrellf** [comment]
I just released a new version, and it lets you edit the data structure. More info here:
http://farrellf.com/projects/software/2020-07-17_Telemetry_Viewer_v0.7/
