### ISSUE TITLE
log string data and print as lable

### ISSUE THREAD

**Issue by binarymaker** [farrellf/TelemetryViewer#27]
just read csv string or number value and print as lable

i want print hex values and message strings.

Ex: printf("%d,%s\n\r", timestamp, "lamp off")

**Comment by farrellf** [comment]
So you just want the telemetry printed out to the console? This software is for visualizing the data, not just printing out text. You might be better served with a terminal program or small custom-written program.

**Comment by binarymaker** [comment]
I want both options. Some data no need to plot.
ex. status ON/OFF, warning messages.

if you develop, it will more use full for all type of projects

Thanks

**Comment by farrellf** [comment]
The next version of TelemetryViewer will have better support for timestamps and for boolean/enum telemetry. But I have no plans to implement what you're asking for. Samples can be exported to a CSV file for later analysis, but the main goal of this program is for visualizing a stream of telemetry data.
