### ISSUE TITLE
Suggestion: Oscilloscope-like chart.

### ISSUE THREAD

**Issue by plamenbe** [farrellf/TelemetryViewer#31]
Great tool, indeed!
Just an idea... after certain amount of sampling points or time, plotting to start from the beginning of the chart. May be it will be useful for Arduino or other projects, imitating oscilloscope.

**Comment by farrellf** [comment]
If you are referring to triggering, the latest release now supports that:

http://www.farrellf.com/projects/software/2021-07-24_Telemetry_Viewer_v0.8/
https://www.youtube.com/watch?v=NUBm9b8YQMQ&t=776s

**Comment by plamenbe** [comment]
Yes, exactly!
The new version is marvelous.
Thank you!
