### ISSUE TITLE
suggestion: digital time clock lookalike card

### ISSUE THREAD

**Issue by thostie2002** [farrellf/TelemetryViewer#34]
i use a real time clock module to import time to the telemetry viewer, now i use 3 dail chards one for hours, one for minutes, one for seconds see the first image.

please can you make a simple digital clock chard? like the second image?

thanks:)

first image
![image](https://user-images.githubusercontent.com/48547379/78369578-b0984e00-75c5-11ea-9754-c6e0befa596b.png)

second image
![image](https://user-images.githubusercontent.com/48547379/78369656-d45b9400-75c5-11ea-88f8-f2e2ee184ee1.png)

**Comment by farrellf** [comment]
I agree, it would be nice to have a simple numeric display. It's on my to do list ;)

**Comment by farrellf** [comment]
The latest release now supports this. There is a "Statistics Chart" and it can be configured to show just the current values:

http://www.farrellf.com/projects/software/2021-07-24_Telemetry_Viewer_v0.8/
https://youtu.be/NUBm9b8YQMQ?t=646
