### ISSUE TITLE
Version 0.7 - gluegen-java-src.zip missing from lib

### ISSUE THREAD

**Issue by greenonline** [farrellf/TelemetryViewer#44]
In the TelemetryViewer_v0.7_src_20200717.zip, from the blog [download](http://www.farrellf.com/TelemetryViewer/) page, in the `lib` directory, the `gluegen-java-src.zip` file is missing.

in TelemetryViewer_v0.6_src_20190908.zip, all four files are present in the `lib` directory:

 - `gluegen-java-src.zip`
 - `gluegen-javadoc.zip`
 - `jogamp-fat-java-src.zip`
 - `jogl-javadoc.zip`

As you state in issue #40 that you have used a newer version of the OpenGL library then this could be an issue with the library itself, rather than an omission on your part.

**Comment by farrellf** [comment]
The gluegen-java-src.zip file is not used at run time. It is just the source code for gluegen. (Useful for software developers trying to understand or maybe debug gluegen.) I found myself needing to peek at the source code for JOGL occasionally, but never needing to look at the gluegen code, so I didn't bother to include it. If you'd like that archive, it is available here:

https://jogamp.org/deployment/v2.4.0-rc-20200307/
