### ISSUE TITLE
serial send

### ISSUE THREAD

**Issue by jschoch** [farrellf/TelemetryViewer#5]
would be nice to be able to send since you can't send with anything else without disconnecting.

**Comment by jcrodriguez40** [comment]
True. 

A workaround might be using 2 serial ports. Many microcontrollers come with several HW serial ports built in. However, even in the case of "poorly-equipped" chips (like some of ATMEL's), you might get away with it by using the "Software_Serial" Library. 

Hope it helps!

**Comment by farrellf** [comment]
I plan to add support for this, but it might be a while before I get to it.

**Comment by farrellf** [comment]
I finally got around to implementing this. It's in the latest release:

http://www.farrellf.com/projects/software/2021-07-24_Telemetry_Viewer_v0.8/
https://www.youtube.com/watch?v=NUBm9b8YQMQ&t=937s

**Comment by jschoch** [comment]
sweet, thanks!
