### ISSUE TITLE
Running Ver 0.8 - Program runs, the buttons at the bottom show, but the grid does  not show

### ISSUE THREAD

**Issue by RaspPiGuy** [farrellf/TelemetryViewer#53]
Running the program from the command line, this exception shows up in several places:
NoSuchMethodError: java.nio.FloatBuffer.rewind()Ljava/nio/FloatBuffer; on thread AWT-EventQueue-0

I'm running Java 8 on Windows 10

**Comment by farrellf** [comment]
It looks like I ended up using some methods that were added after Java 8. Java 9 or newer is probably required.

**Comment by RaspPiGuy** [comment]
I installed Java 15 and it all works.  Thanks

**Comment by farrellf** [comment]
In the next release I plan to use some features that were added after Java 8, so I'm going to close this issue because I don't plan to support Java 8 in the future. Glad it works for you now.
