### ISSUE TITLE
v0.8 GUI doesn't load

### ISSUE THREAD

**Issue by SteamLearningLabs** [farrellf/TelemetryViewer#56]
v0.7 GUI will load and I can create graphs by clicking and dragging, but v0.8 is completely blank with not gridlines. I can add a connection, but nothing displays. I updated my graphics drivers, Java, and JRE. 
Any advice?

**Comment by farrellf** [comment]
Hi. Version 0.8 used some features that were added in Java 9. Upgrading to Java 9 or newer should fix the problems.

If you still have problems, please run the program from the command line (with "java --illegal-access=permit -jar TelemetryViewer_v0.8.jar") and share all of the text that gets printed out to the console.

**Comment by BoudjemaaAKHAM** [comment]
Hi, I also had a very similar problem, the gui is displayed, I can add connections but nothing is displayed correctly afterwards. Here are screenshots of the output of the command " java --illegal-access = permit -jar TelemetryViewer_v0.8.jar "
![TV](https://user-images.githubusercontent.com/51098568/146571525-ce4c026d-aa5f-4856-b1a9-29559a998359.PNG)
![TV2](https://user-images.githubusercontent.com/51098568/146571550-9193d86c-74f4-450d-9ed2-73af121cc793.PNG)
your help would be very precious :)

**Comment by farrellf** [comment]
It looks like your graphics driver does not support a modern version of OpenGL, or maybe this is a bug in the OpenGL library that I use. What graphics card do you have? Are you able to run any other software that uses OpenGL (3D games, etc.) ?

**Comment by BoudjemaaAKHAM** [comment]
I have an Intel (R) UHD graphics and an NVIDIA Quadro T1000. It works perfectly on Windows, but when I run it on wsl I had this issue. I don't have any software that uses OpenGL on my system.

**Comment by farrellf** [comment]
It looks like WSL does not officially support OpenGL:
https://github.com/microsoft/WSL/issues/2855

Why are you trying to run it on WSL? Telemetry Viewer works fine directly on Windows.

**Comment by BoudjemaaAKHAM** [comment]
Okay I see, didn't knew about that. Thank you. 

I want to create a docker image of the Telemetry Viewer, so if it works on wsl it will certanly work fine on docker.

**Comment by BoudjemaaAKHAM** [comment]
Hi again ! I got a perfect display on WSL by using VcXsrv instead of Xming and setting this environment variable 'export LIBGL_ALWAYS_INDIRECT=1'
But now I have this openGL error :
![Capture PNG_opengl_bug](https://user-images.githubusercontent.com/51098568/147230246-6c7eb88d-7972-448d-a350-78ce269e210e.PNG)
Do you have any idea about this issue ?

**Comment by farrellf** [comment]
That's not an error. It's just information printed out because it can be helpful in figuring out problems if they occur later on.

**Comment by BoudjemaaAKHAM** [comment]
Perfect ! Thank you so much.

**Comment by Gadgeteering** [comment]
I had some problems loading v0.8 on OSX I had to comment out some JFrame lines in main.java to get it to work


`window.setSize(window.getPreferredSize())`
`//window.setMinimumSize(window.getMinimumSize())`
`window.setLocationRelativeTo(null)`
`//window.setExtendedState(JFrame.MAXIMIZED_BOTH)
`



`2022-03-11 17:19:46.653   [HINT    ]   Start by connecting to a device or opening a file by using the buttons below.
2022-03-11 17:21:16.720   [DEBUG   ]   OpenGL Information:
GL_VENDOR                    = Intel Inc.
GL_RENDERER                  = Intel Iris OpenGL Engine
GL_VERSION                   = 4.1 INTEL-16.5.4
GL_SHADING_LANGUAGE_VERSION  = 4.10
GL_MAJOR_VERSION             = 4
GL_MINOR_VERSION             = 1
GL_MAX_SAMPLES               = 8
GL_MAX_TEXTURE_SIZE          = 16384
GL_MAX_RENDERBUFFER_SIZE     = 16384
GL_MAX_VIEWPORT_DIMS         = 16384 x 16384
GL_MAX_DRAW_BUFFERS          = 8
GL_MAX_COLOR_TEXTURE_SAMPLES = 8
45 EXTENSIONS: GL_ARB_blend_func_extended, GL_ARB_draw_buffers_blend, GL_ARB_draw_indirect, GL_ARB_ES2_compatibility, GL_ARB_explicit_attrib_location, GL_ARB_gpu_shader_fp64, GL_ARB_gpu_shader5, GL_ARB_instanced_arrays, GL_ARB_internalformat_query, GL_ARB_occlusion_query2, GL_ARB_sample_shading, GL_ARB_sampler_objects, GL_ARB_separate_shader_objects, GL_ARB_shader_bit_encoding, GL_ARB_shader_subroutine, GL_ARB_shading_language_include, GL_ARB_tessellation_shader, GL_ARB_texture_buffer_object_rgb32, GL_ARB_texture_cube_map_array, GL_ARB_texture_gather, GL_ARB_texture_query_lod, GL_ARB_texture_rgb10_a2ui, GL_ARB_texture_storage, GL_ARB_texture_swizzle, GL_ARB_timer_query, GL_ARB_transform_feedback2, GL_ARB_transform_feedback3, GL_ARB_vertex_attrib_64bit, GL_ARB_vertex_type_2_10_10_10_rev, GL_ARB_viewport_array, GL_EXT_debug_label, GL_EXT_debug_marker, GL_EXT_framebuffer_multisample_blit_scaled, GL_EXT_texture_compression_s3tc, GL_EXT_texture_filter_anisotropic, GL_EXT_texture_sRGB_decode, GL_APPLE_client_storage, GL_APPLE_container_object_shareable, GL_APPLE_flush_render, GL_APPLE_object_purgeable, GL_APPLE_rgb_422, GL_APPLE_row_bytes, GL_APPLE_texture_range, GL_ATI_texture_mirror_once, GL_NV_texture_barrier
`

**Comment by farrellf** [comment]
@SteamLearningLabs Are you still having problems with the software? I'd like to close this issue if it has been resolved.

**Comment by SteamLearningLabs** [comment]
v7 works, but I could never get v8 to work. I tried on several computers
and laptops with no luck.

**Comment by farrellf** [comment]
Can you run the program from the command line (with "java --illegal-access=permit -jar TelemetryViewer_v0.8.jar") and share all of the text that gets printed out to the console?

**Comment by Wayfel** [comment]
TelemetryViewer v0.8 is completely blank with no gridlines. I can add a connection, but nothing displays (No Grids).
To correct this issue I downloaded jdk-11.0.18_Windows-x64_bin.exe. at https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html. I have Windows 10 with Java 8 with update 241 build 1.8.0_241 b07 installed. After the install the TelemetryViewer v0.8 worked fine.

**Comment by flexi256** [comment]
Had the same issue with TelemetryViewer v0.8 being blank with no gridlines. The jdk-11.0.18_Windows-x64_bin.exe  also resolved it for me.
