### ISSUE TITLE
Grid Section Not Displaying

### ISSUE THREAD

**Issue by marksmith24** [farrellf/TelemetryViewer#64]
After connecting and defining the data definitions, the grid section and settings menu are not displaying. Moreover, the settings menu becomes visible upon clicking on the left-hand side menu. However, the same cannot be said for the grid section, as it remains invisible.

![Grid Section Not Displaying](https://user-images.githubusercontent.com/6470815/234454469-f3c1781d-07cd-48d5-940e-233a85c20079.PNG)

**Comment by farrellf** [comment]
I'm guessing you are using Java 16 or newer. See here for details:
http://www.farrellf.com/projects/software/2021-07-24_Telemetry_Viewer_v0.8/
