### ISSUE TITLE
Serial over Bluetooth (Rfcomm)

### ISSUE THREAD

**Issue by vsaljooghi** [farrellf/TelemetryViewer#9]
Hello

Big thanks for the great job you have done. 
I want to plot data that comes through Bluetooth from Arduino. I am able to receive data on /dev/rfcomm0. But unfortunately, this device node will not be enumerated in Telemetry GUI. I went through the source code and saw that the following function is responsible for it: SerialPort.getCommPorts().

Could please give me some hint on how to solve this issue?

Best Regards,

**Comment by farrellf** [comment]
I use an HC-06 Bluetooth module in Windows 10 with no problems. I'm guessing this might be an issue with the serial port library I use. Could you try the same Bluetooth module with a Windows computer to see if the problem only occurs in Linux?

**Comment by farrellf** [comment]
Unable to duplicate this problem, and no response after months, so I'm closing this issue.
